version: "3"

services:
  nginx_wrap:
    build: .
    container_name: vidikon_nwrap
    ports:
      - 11111:80
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/http.d:/etc/nginx/http.d
      - ./data:/var/sh/cgi
      - ./html:/var/www/html
    links:
      - couchserver

  couchserver:
    image: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./base:/opt/couchdb/data

  activemq:
    image: symptoma/activemq:latest
    container_name: 'activemq'
    ports:
      - 61616:61616
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activemq
