version: "3"

services: 
  nginx_wrap:
    build: .
    container_name: dmatukhin_nwrap
    ports:
      - 8100:80
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/http.d:/etc/nginx/http.d
      - ./data:/var/sh/cgi
      - ./html:/var/www/html
  couchDB:
    image: couchdb
    restart: unless-stopped
    ports:
      - 8110:5984
    enviroment:
      COUCHDB_USER=admin1
      COUCHDB_PASSWORD=admin1
    volume:
      - ./base:/opt/couchdb/data
