version: "3"

services: 
  nginx_wrap:
    build: .
    container_name: vidikon_nwrap
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/http.d:/etc/nginx/http.d
      - ./data:/var/sh/cgi
      - ./html:/var/www/html
